In [ ]:
Assignment-11 29-06-2026 
Adarsh Rai 

In [1]:
# 1. Combining a 1D and 2D NumPy Array
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([[4, 5, 6],
                 [7, 8, 9]])

result = np.vstack((arr1, arr2))

print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# 2. Flatten a 2D NumPy Array into 1D Array
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()

print(flat)

[1 2 3 4 5 6]


In [3]:
# 3. Reverse a NumPy Array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original:", arr)
print("Reversed:", arr[::-1])

Original: [10 20 30 40 50]
Reversed: [50 40 30 20 10]


In [4]:
# 4. NumPy Array Operations
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

# Maximum
print("Maximum:", np.max(arr))

# Minimum
print("Minimum:", np.min(arr))

# Rows and Columns
print("Rows:", arr.shape[0])
print("Columns:", arr.shape[1])

# All elements
print("\nAll Elements:")
for row in arr:
    for element in row:
        print(element)

# Specific element
print("\nSpecific Element:", arr[1,1])

# Sum using for loop
total = 0
for row in arr:
    for element in row:
        total += element

print("Sum:", total)

Maximum: 60
Minimum: 10
Rows: 2
Columns: 3

All Elements:
10
20
30
40
50
60

Specific Element: 50
Sum: 210


In [5]:
# Adding, Subtracting, Multiplying, Dividing Arrays
import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,5])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [6]:
# 5. Iterate 3D Array Using For Loop and nditer
import numpy as np

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("Using nested loops:")

for x in arr:
    for y in x:
        for z in y:
            print(z)

print("\nUsing nditer:")

for i in np.nditer(arr):
    print(i)

Using nested loops:
1
2
3
4
5
6
7
8

Using nditer:
1
2
3
4
5
6
7
8


In [8]:
# 6. Mean, Median and Mode of Two 2D Arrays
import numpy as np
from scipy import stats

arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([[7,8,9],
                 [10,11,12]])

combined = np.concatenate((arr1, arr2))

print("Combined Array:")
print(combined)

print("Mean:", np.mean(combined))
print("Median:", np.median(combined))

mode_result = stats.mode(combined, axis=None)

print("Mode:", mode_result.mode)

Combined Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Mean: 6.5
Median: 6.5
Mode: 1
