In [ ]:
Assignment-10 28-06-2026 
Adarsh Rai 

In [1]:
# 1. Replace NaN with 0 and interchange rows and columns
import numpy as np

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

print("Original Array:")
print(arr)

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

print("\nAfter Replacing NaN with 0:")
print(arr)

# Interchange rows
rows_swapped = arr[::-1]
print("\nRows Interchanged:")
print(rows_swapped)

# Interchange columns
cols_swapped = arr[:, ::-1]
print("\nColumns Interchanged:")
print(cols_swapped)

Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

After Replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

Rows Interchanged:
[[   0.   -8.    0.   94.]
 [   6.   -8.   73. -110.]]

Columns Interchanged:
[[-110.   73.   -8.    6.]
 [  94.    0.   -8.    0.]]


In [2]:
# 2. Move axes of a 3D array to new positions
import numpy as np

arr3d = np.arange(24).reshape(2, 3, 4)

print("Original Shape:", arr3d.shape)

new_arr = np.moveaxis(arr3d, 0, 2)

print("New Shape:", new_arr.shape)
print(new_arr)

Original Shape: (2, 3, 4)
New Shape: (3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
