In [ ]:
Assignment 13 1-06-2026
Adarsh Rai 

In [1]:
# 1) Replace NaN with 0 and interchange rows and columns
import numpy as np

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

print("Original Array:")
print(arr)

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

print("\nAfter Replacing NaN with 0:")
print(arr)

# Interchange rows
row_swapped = arr[[1, 0], :]
print("\nRows Interchanged:")
print(row_swapped)

# Interchange columns
col_swapped = arr[:, [3, 2, 1, 0]]
print("\nColumns Interchanged:")
print(col_swapped)

Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

After Replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

Rows Interchanged:
[[   0.   -8.    0.   94.]
 [   6.   -8.   73. -110.]]

Columns Interchanged:
[[-110.   73.   -8.    6.]
 [  94.    0.   -8.    0.]]


In [2]:
# 2) Move axes of 3D array to new positions
import numpy as np

arr = np.arange(24).reshape(2,3,4)

print("Original Shape:", arr.shape)

new_arr = np.moveaxis(arr, 0, 2)

print("New Shape:", new_arr.shape)
print(new_arr) 

Original Shape: (2, 3, 4)
New Shape: (3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [3]:
# 3) Replace NaN values with average of columns
import numpy as np

arr = np.array([[1, np.nan, 3],
                [4, 5, np.nan],
                [7, 8, 9]])

col_mean = np.nanmean(arr, axis=0)

inds = np.where(np.isnan(arr))

arr[inds] = np.take(col_mean, inds[1])

print(arr)

[[1.  6.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [4]:
# 4) Replace negative values with zero
import numpy as np

arr = np.array([6, -8, 73, -110, 25])

arr[arr < 0] = 0

print(arr)

[ 6  0 73  0 25]


In [5]:
# 5) Average, Mean, Median, Mode of two NumPy 2D arrays
import numpy as np
from scipy import stats

arr1 = np.array([[3,4],
                 [5,6]])

arr2 = np.array([[1,0],
                 [7,8]])

avg = (arr1 + arr2)/2

print("Average Array:")
print(avg)

print("Mean =", np.mean(avg))
print("Median =", np.median(avg))

mode = stats.mode(avg, axis=None)
print("Mode =", mode.mode)

Average Array:
[[2. 2.]
 [6. 7.]]
Mean = 4.25
Median = 4.0
Mode = 2.0


In [6]:
# 6) Solve equation using linalg() and Inverse Matrix
#Equations:
# x−2y+3z=9
# −x+3y−z=−6
# 2x−5y+5z=17
import numpy as np

A = np.array([[1,-2,3],
              [-1,3,-1],
              [2,-5,5]])

B = np.array([9,-6,17])

# Using linalg.solve()
solution = np.linalg.solve(A,B)

print("Using linalg.solve():")
print(solution)

# Using inverse matrix
A_inv = np.linalg.inv(A)

solution2 = A_inv.dot(B)

print("\nUsing Inverse Matrix:")
print(solution2)

Using linalg.solve():
[ 1. -1.  2.]

Using Inverse Matrix:
[ 1. -1.  2.]
